spring:
  application:
    name: backend
    # in application.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sooktin
    username: admin
    password: cos0000
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

logging:
  level:
    io:
      netty: DEBUG

jwt:
  issuer: okm
  access-expiration: 360000
  secret-key: cThIIoDvwdueQB468K5xDc5633seEFoqwxjF_xSJyQQ